steps:
- name: 'gcr.io/cloud-builders/bazel:7.3.2'
  entrypoint: 'bazel'
  args: ['build', '--curses=no', '//:all']
- name: 'gcr.io/cloud-builders/bazel:7.3.2'
  entrypoint: 'bazel'
  args: ['test', '--test_output=all', '--curses=no', '//:all']
- name: 'gcr.io/cloud-builders/bazel:7.3.2'
  entrypoint: 'bazel'
  dir: 'example_bazel'
  args: ['build', '--curses=no', '//:all']
- name: 'gcr.io/cloud-builders/bazel:7.3.2'
  entrypoint: 'bazel'
  dir: 'example_bazel'
  args: ['test', '--test_output=all', '--curses=no', '//:all']
